defaults: &defaults
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint:ci
  format:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn format:ci
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn run test:ci
      - persist_to_workspace:
          root: .
          paths:
            - coverage
  coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cat coverage/lcov.info | npx coveralls
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    resource_class: small
    docker:
      - image: quay.io/reciprocity/build-base:v0.6.7
        auth:
          username: $QUAY_USERNAME
          password: $QUAY_PASSWORD
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload build except index.html with cache headers
          command: cd public && aws s3 sync . s3://zen-ui.zengrc.com --delete

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - format:
          requires:
            - lint
      - test:
          requires:
            - prepare
      - coverage:
          requires:
            - test
      - build:
          requires:
            - prepare
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
